"""add ingredient cost per base

Revision ID: 0a9e68b4db2c
Revises: 6652170182e5
Create Date: 2026-01-11 17:21:49.951641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9e68b4db2c'
down_revision: Union[str, Sequence[str], None] = '6652170182e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('current_cost_per_base_unit', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'current_cost_per_base_unit')
    # ### end Alembic commands ###
