"""Added Logging to Debug/ General Database Update

Revision ID: 18dbd9c54763
Revises: cba24c5efbf6
Create Date: 2026-01-14 19:52:16.052735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18dbd9c54763'
down_revision: Union[str, Sequence[str], None] = 'cba24c5efbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
