"""Finalize Costing Changes

Revision ID: 565be8bac016
Revises: 0a9e68b4db2c
Create Date: 2026-01-11 19:07:22.274649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565be8bac016'
down_revision: Union[str, Sequence[str], None] = '0a9e68b4db2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'current_cost_per_base_unit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'current_cost_per_base_unit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    # ### end Alembic commands ###
